
import QtQuick 2.0

pragma Singleton

/* Global QML Style Object */
QtObject {

    property QtObject border: QtObject {

        property QtObject color: QtObject {
            property color disabled: "red"
            property color focus: "blue"
            property color normal: "gray"
        }

        property QtObject width: QtObject {
            property int big: 3
            property int normal: 1
        }
    }

    property QtObject fontawesome: QtObject {
        property string source: "qrc:/fonts/fontawesome-webfont.ttf"
        property string family: "FontAwesome"

        property QtObject icon: QtObject {
            property string glass               : "\uf000"
            property string music               : "\uf001"
            property string search              : "\uf002"
            property string envelope            : "\uf003"
            property string heart               : "\uf004"
            property string star                : "\uf005"
            property string starEmpty           : "\uf006"
            property string user                : "\uf007"
            property string film                : "\uf008"
            property string thLarge             : "\uf009"
            property string th                  : "\uf00a"
            property string thList              : "\uf00b"
            property string ok                  : "\uf00c"
            property string remove              : "\uf00d"
            property string zoomIn              : "\uf00e"
            property string zoomOut             : "\uf010"
            property string off                 : "\uf011"
            property string signal              : "\uf012"
            property string cog                 : "\uf013"
            property string trash               : "\uf014"
            property string home                : "\uf015"
            property string file                : "\uf016"
            property string time                : "\uf017"
            property string road                : "\uf018"
            property string downloadAlt         : "\uf019"
            property string download            : "\uf01a"
            property string upload              : "\uf01b"
            property string inbox               : "\uf01c"
            property string playCircle          : "\uf01d"
            property string repeat              : "\uf01e"
            property string refresh             : "\uf021"
            property string listAlt             : "\uf022"
            property string lock                : "\uf023"
            property string flag                : "\uf024"
            property string headphones          : "\uf025"
            property string volumeOff           : "\uf026"
            property string volumeDown          : "\uf027"
            property string volumeUp            : "\uf028"
            property string qrcode              : "\uf029"
            property string barcode             : "\uf02a"
            property string tag                 : "\uf02b"
            property string tags                : "\uf02c"
            property string book                : "\uf02d"
            property string bookmark            : "\uf02e"
            property string print_               : "\uf02f"
            property string camera              : "\uf030"
            property string font                : "\uf031"
            property string bold                : "\uf032"
            property string italic              : "\uf033"
            property string textHeight          : "\uf034"
            property string textWidth           : "\uf035"
            property string alignLeft           : "\uf036"
            property string alignCenter         : "\uf037"
            property string alignRight          : "\uf038"
            property string alignJustify        : "\uf039"
            property string list                : "\uf03a"
            property string indentLeft          : "\uf03b"
            property string indentRight         : "\uf03c"
            property string facetimeVideo       : "\uf03d"
            property string picture             : "\uf03e"
            property string pencil              : "\uf040"
            property string mapMarker           : "\uf041"
            property string adjust              : "\uf042"
            property string tint                : "\uf043"
            property string edit                : "\uf044"
            property string share               : "\uf045"
            property string check               : "\uf046"
            property string move                : "\uf047"
            property string stepBackward        : "\uf048"
            property string stepForward         : "\uf049"
            property string backward            : "\uf04a"
            property string play                : "\uf04b"
            property string pause               : "\uf04c"
            property string stop                : "\uf04d"
            property string forward             : "\uf04e"
            property string fastForward         : "\uf050"
            // property string stepForward         : "\uf051"
            property string eject               : "\uf052"
            property string chevronLeft         : "\uf053"
            property string chevronRight        : "\uf054"
            property string plusSign            : "\uf055"
            property string minusSign           : "\uf056"
            property string removeSign          : "\uf057"
            property string okSign              : "\uf058"
            property string questionSign        : "\uf059"
            property string infoSign            : "\uf05a"
            property string screenshot          : "\uf05b"
            property string removeCircle        : "\uf05c"
            property string okCircle            : "\uf05d"
            property string banCircle           : "\uf05e"
            property string arrowLeft           : "\uf060"
            property string arrowRight          : "\uf061"
            property string arrowUp             : "\uf062"
            property string arrowDown           : "\uf063"
            property string shareAlt            : "\uf064"
            property string resizeFull          : "\uf065"
            property string resizeSmall         : "\uf066"
            property string plus                : "\uf067"
            property string minus               : "\uf068"
            property string asterish            : "\uf069"
            property string exclamationSign     : "\uf06a"
            property string gift                : "\uf06b"
            property string leave               : "\uf06c"
            property string fire                : "\uf06d"
            property string eyeOpen             : "\uf06e"
            property string eyeClose            : "\uf070"
            property string warningSign         : "\uf071"
            property string plane               : "\uf072"
            property string calendar            : "\uf073"
            property string random              : "\uf074"
            property string comment             : "\uf075"
            property string magnet              : "\uf076"
            property string chevronUp           : "\uf077"
            property string chevronDown         : "\uf078"
            property string retweet             : "\uf079"
            property string shoppingCart        : "\uf07a"
            property string folderClose         : "\uf07b"
            property string folderOpen          : "\uf07c"
            property string resizeVertical      : "\uf07d"
            property string resizeHorizontal    : "\uf07e"
            property string barChart            : "\uf080"
            property string twitterSign         : "\uf081"
            property string facebookSign        : "\uf082"
            property string cameraRetro         : "\uf083"
            property string key                 : "\uf084"
            property string cogs                : "\uf085"
            property string comments            : "\uf086"
            property string thumbsUp            : "\uf087"
            property string thumbsDown          : "\uf088"
            property string starHalf            : "\uf089"
            property string heartEmpty          : "\uf08a"
            property string signout             : "\uf08b"
            property string linkedinSign        : "\uf08c"
            property string pushpin             : "\uf08d"
            property string externalLink        : "\uf08e"
            property string signin              : "\uf090"
            property string trophy              : "\uf091"
            property string githubSign          : "\uf092"
            property string uploadAlt           : "\uf093"
            property string lemon               : "\uf094"
            property string phone               : "\uf095"
            property string checkEmpty          : "\uf096"
            property string bookmarkEmpty       : "\uf097"
            property string phoneSign           : "\uf098"
            property string twitter             : "\uf099"
            property string facebook            : "\uf09a"
            property string github              : "\uf09b"
            property string unlock              : "\uf09c"
            property string creditCard          : "\uf09d"
            property string rss                 : "\uf09e"
            property string hdd                 : "\uf0a0"
            property string bullhorn            : "\uf0a1"
            property string bell                : "\uf0a2"
            property string certificate         : "\uf0a3"
            property string handRight           : "\uf0a4"
            property string handLeft            : "\uf0a5"
            property string handUp              : "\uf0a6"
            property string handDown            : "\uf0a7"
            property string circleArrowLeft     : "\uf0a8"
            property string circleArrowRight    : "\uf0a9"
            property string circleArrowUp       : "\uf0aa"
            property string circleArrowDown     : "\uf0ab"
            property string globe               : "\uf0ac"
            property string wrench              : "\uf0ad"
            property string tasks               : "\uf0ae"
            property string filter              : "\uf0b0"
            property string briefcase           : "\uf0b1"
            property string fullscreen          : "\uf0b2"
            property string group               : "\uf0c0"
            property string link                : "\uf0c1"
            property string cloud               : "\uf0c2"
            property string beaker              : "\uf0c3"
            property string cut                 : "\uf0c4"
            property string copy                : "\uf0c5"
            property string paperClip           : "\uf0c6"
            property string save                : "\uf0c7"
            property string signBlank           : "\uf0c8"
            property string reorder             : "\uf0c9"
            property string listUl              : "\uf0ca"
            property string listOl              : "\uf0cb"
            property string strikethrough       : "\uf0cc"
            property string underline           : "\uf0cd"
            property string table               : "\uf0ce"
            property string magic               : "\uf0d0"
            property string truck               : "\uf0d1"
            property string pinterest           : "\uf0d2"
            property string pinterestSign       : "\uf0d3"
            property string googlePlusSign      : "\uf0d4"
            property string googlePlus          : "\uf0d5"
            property string money               : "\uf0d6"
            property string caretDown           : "\uf0d7"
            property string caretUp             : "\uf0d8"
            property string caretLeft           : "\uf0d9"
            property string caretRight          : "\uf0da"
            property string columns             : "\uf0db"
            property string sort                : "\uf0dc"
            property string sortDown            : "\uf0dd"
            property string sortUp              : "\uf0de"
            property string envelopeAlt         : "\uf0e0"
            property string linkedin            : "\uf0e1"
            property string undo                : "\uf0e2"
            property string legal               : "\uf0e3"
            property string dashboard           : "\uf0e4"
            property string commentAlt          : "\uf0e5"
            property string commentsAlt         : "\uf0e6"
            property string bolt                : "\uf0e7"
            property string sitemap             : "\uf0e8"
            property string unbrella            : "\uf0e9"
            property string paste               : "\uf0ea"
            property string userMd              : "\uf200"
        }
    }

    property QtObject window: QtObject {
        property color background: "white"
    }
}
